language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Home of Travis CI Server
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# Alarm to mail when CI complete
notifications:
  email:
    recipients:
      ihaeeun16@gmail.com